parameters:
#    users_management.example.class: Users\ManagementBundle\Example

#services:
#    users_management.example:
#        class: %users_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    
    ## PASSWORD HASH HELPERS
    sha256salted_encoder:
        class: Users\ManagementBundle\Helper\Sha256SaltedHelper

    ## SENDING OF EMAIL HELPERS
    service_emailer:
        class: Users\ManagementBundle\Helper\MailHelper
        arguments: [@mailer]

    ## CONSTANTS
    CONSTANTS:
        class: Users\ManagementBundle\Helper\Constants