parameters:
#    users_management.example.class: Users\ManagementBundle\Example

#services:
#    users_management.example:
#        class: %users_management.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    
    ## HELPERS
    sha256salted_encoder:
        class: Users\ManagementBundle\Helper\Sha256SaltedHelper
    service_emailer:
        class: Users\ManagementBundle\Helper\MailHelper
        arguments: [@mailer]